---
- name: Check required vars
  ansible.builtin.include_tasks:
    file: check_vars.yml
    apply:
      tags:
        - redis
        - redis:check
        - check
  tags:
    - always

- name: Install redis
  ansible.builtin.include_tasks:
    file: redis_install.yml
    apply:
      tags:
        - redis
        - redis:install
  tags:
    - always

- name: Configure redis
  ansible.builtin.include_tasks:
    file: redis_configure.yml
    apply:
      tags:
        - redis
        - redis:config
  tags:
    - always

- name: Configure sentinel
  ansible.builtin.include_tasks:
    file: redis_sentinel.yml
    apply:
      tags:
        - redis
        - redis:sentinel
  when: redis_sentinel_server_group | default(false)
  tags:
    - always

- name: Datadoc suport
  ansible.builtin.include_tasks:
    file: redis_datadog.yml
    apply:
      tags:
        - redis
        - redis:redis:sentinel
        - datadog
        - redis:datadog
  when: datadog_enabled | default(false)
  tags:
    - always

- name: Backup setup
  ansible.builtin.include_tasks:
    file: redis_backup.yml
    apply:
      tags:
        - redis
        - redis:sentinel
        - datadog
        - backup
  when: redis_rdb_backup_keep > 0
  tags:
    - always
