---
- name: Deploys datadog integration
  ansible.builtin.template:
    src: datadog.yml.j2
    dest: /etc/dd-agent/conf.d/redisdb.yaml
    mode: "0640"
    owner: dd-agent
    group: dd-agent
  when: datadog_api_key is defined and datadog_api_key
  notify: Restart datadog-agent
