---
# yamllint disable rule:line-length
- name: Restart redis
  ansible.builtin.service:
    name: redis-server
    state: restarted
  notify:
    - Find default Redis interface
    - Find explicit Redis interface
    - Check redis

- name: Find default Redis interface
  ansible.builtin.set_fact:
    __redis_listen_ip: "{{ ansible_default_ipv4.address }}"

- name: Find explicit Redis interface
  ansible.builtin.set_fact:
    __redis_listen_ip: "{{ hostvars[inventory_hostname]['ansible_' + redis_bind_interface].ipv4.address }}"
  when: 'redis_bind_interface != "all"'

- name: Check redis
  ansible.builtin.wait_for:
    host: "{{ __redis_listen_ip }}"
    port: "{{ redis_port }}"
    timeout: 10

- name: Restart sentinel
  ansible.builtin.service:
    name: redis-sentinel
    state: restarted
  notify: Check sentinel

- name: Check sentinel
  ansible.builtin.wait_for:
    host: "{{ redis_sentinel_bind }}"
    port: "{{ redis_sentinel_port }}"
    timeout: 10
